server:
    port: 8086
spring:
    datasource:
        password: ''
        url: jdbc:mysql://localhost:3306/library
        username: root
jpa:
    hibernate:
        ddl-auto: update
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
            format_sql: true
        show-sql: true